### ISSUE TITLE
Additional kernel arguments not being parsed

### ISSUE THREAD

**Issue by jswent** [tspink/stacsos#2]
# Issue: Kernel only parses first command-line argument

## Description
Currently, when multiple kernel arguments are passed at boot time, only the first argument is being parsed and stored correctly. Subsequent arguments are ignored.

## Steps to Reproduce
1. Build the kernel
2. Run the kernel with multiple arguments:
   ```
   make run kernel-args="any-arg=test sched=rr"
   ```
3. Check the scheduler that is being used.

## Expected Behavior
All provided kernel arguments should be parsed and stored correctly. In the example above, we expect:
- `sched` to be set to `rr`

## Actual Behavior
Only the first argument is parsed, and therefore the `rr` scheduler is not being used.

## Proposed Solution
Issue has been addressed in PR #1

**Comment by tspink** [comment]
Merged
